version: '3.4'

services:
  rbssJSparticipant:
    image: git.tu-berlin.de:5000/ods-pj/rbssf2122/java:latest
    environment:       
      - isRBSSTester=false       
      - p2pContactIP=rbssJSparticipant
      - p2pContactPort=7042
    ports:
      - "5634:7042"
  rbss_cs_initiator:
    build:
      context: .
      dockerfile: RBSS_CS/Dockerfile
    ports:
      - "5633:80"
    environment:
      - RBSS_CONNECTION=http://rbssJSparticipant:7042
    entrypoint: sh -c "cp -f settings-testing.yml settings.yml && dotnet RBSS_CS.dll"
    depends_on:
      - rbssJSparticipant
