testingMode: true
testingModeInitiator: true
auxiliaryDS: DAL1.RBSS_CS.Datastructures.RedBlackTreePersistence
dbKind: none
hashFunc: DAL1.RBSS_CS.Hashfunction.StableHash
bifunctor: DAL1.RBSS_CS.Bifunctors.XorBifunctor
useIntervalForSync: true
syncIntervalMs: -1
branchingFactor: 6
itemSize: 4
p2PStructure: RING
