/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InlineObject1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InlineObject1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InlineObject1
        //private InlineObject1 instance;

        public InlineObject1Tests()
        {
            // TODO uncomment below to create an instance of InlineObject1
            //instance = new InlineObject1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InlineObject1
        /// </summary>
        [Fact]
        public void InlineObject1InstanceTest()
        {
            // TODO uncomment below to test "IsType" InlineObject1
            //Assert.IsType<InlineObject1>(instance);
        }


        /// <summary>
        /// Test the property 'IdFrom'
        /// </summary>
        [Fact]
        public void IdFromTest()
        {
            // TODO unit test for the property 'IdFrom'
        }
        /// <summary>
        /// Test the property 'IdNext'
        /// </summary>
        [Fact]
        public void IdNextTest()
        {
            // TODO unit test for the property 'IdNext'
        }
        /// <summary>
        /// Test the property 'FpOfData'
        /// </summary>
        [Fact]
        public void FpOfDataTest()
        {
            // TODO unit test for the property 'FpOfData'
        }

    }

}
