/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InsertStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InsertStepTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InsertStep
        //private InsertStep instance;

        public InsertStepTests()
        {
            // TODO uncomment below to create an instance of InsertStep
            //instance = new InsertStep();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InsertStep
        /// </summary>
        [Fact]
        public void InsertStepInstanceTest()
        {
            // TODO uncomment below to test "IsType" InsertStep
            //Assert.IsType<InsertStep>(instance);
        }


        /// <summary>
        /// Test the property 'IdFrom'
        /// </summary>
        [Fact]
        public void IdFromTest()
        {
            // TODO unit test for the property 'IdFrom'
        }
        /// <summary>
        /// Test the property 'IdNext'
        /// </summary>
        [Fact]
        public void IdNextTest()
        {
            // TODO unit test for the property 'IdNext'
        }
        /// <summary>
        /// Test the property 'IdTo'
        /// </summary>
        [Fact]
        public void IdToTest()
        {
            // TODO unit test for the property 'IdTo'
        }
        /// <summary>
        /// Test the property 'DataToInsert'
        /// </summary>
        [Fact]
        public void DataToInsertTest()
        {
            // TODO unit test for the property 'DataToInsert'
        }
        /// <summary>
        /// Test the property 'Handled'
        /// </summary>
        [Fact]
        public void HandledTest()
        {
            // TODO unit test for the property 'Handled'
        }

    }

}
