/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Client;
using System.Reflection;
using Models.RBSS_CS;
using Newtonsoft.Json;
using Xunit.Abstractions;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SimpleDataObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimpleDataObjectTests : IDisposable
    {
        private readonly ITestOutputHelper _testOutputHelper;

        // TODO uncomment below to declare an instance variable for SimpleDataObject
        private SimpleDataObject instance;

        public SimpleDataObjectTests(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
            // TODO uncomment below to create an instance of SimpleDataObject
            instance = new SimpleDataObject("eel", "string");
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimpleDataObject
        /// </summary>
        [Fact]
        public void SimpleDataObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimpleDataObject
            Assert.IsType<SimpleDataObject>(instance);
            Assert.Equal(instance.GetHashCode(), new SimpleDataObject("eel", "string").GetHashCode());
            _testOutputHelper.WriteLine("Hash: " + instance.GetHashCode());
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AdditionalProperties'
        /// </summary>
        [Fact]
        public void AdditionalPropertiesTest()
        {
            // TODO unit test for the property 'AdditionalProperties'
        }

    }

}
