/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Step
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StepTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Step
        //private Step instance;

        public StepTests()
        {
            // TODO uncomment below to create an instance of Step
            //instance = new Step();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Step
        /// </summary>
        [Fact]
        public void StepInstanceTest()
        {
            // TODO uncomment below to test "IsType" Step
            //Assert.IsType<Step>(instance);
        }


        /// <summary>
        /// Test the property 'TimeSent'
        /// </summary>
        [Fact]
        public void TimeSentTest()
        {
            // TODO unit test for the property 'TimeSent'
        }
        /// <summary>
        /// Test the property 'CurrentStep'
        /// </summary>
        [Fact]
        public void CurrentStepTest()
        {
            // TODO unit test for the property 'CurrentStep'
        }

    }

}
