/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ValidateStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidateStepTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidateStep
        //private ValidateStep instance;

        public ValidateStepTests()
        {
            // TODO uncomment below to create an instance of ValidateStep
            //instance = new ValidateStep();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidateStep
        /// </summary>
        [Fact]
        public void ValidateStepInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidateStep
            //Assert.IsType<ValidateStep>(instance);
        }


        /// <summary>
        /// Test the property 'IdFrom'
        /// </summary>
        [Fact]
        public void IdFromTest()
        {
            // TODO unit test for the property 'IdFrom'
        }
        /// <summary>
        /// Test the property 'IdTo'
        /// </summary>
        [Fact]
        public void IdToTest()
        {
            // TODO unit test for the property 'IdTo'
        }
        /// <summary>
        /// Test the property 'FpOfData'
        /// </summary>
        [Fact]
        public void FpOfDataTest()
        {
            // TODO unit test for the property 'FpOfData'
        }

    }

}
