testingMode: true
testingModeInitiator: true
auxillaryDS: DAL1.RBSS_CS.Datastructures.SortedSetPersistence
dbKind: none
hashFunc: DAL1.RBSS_CS.Hashfunction.StableHash
bifunctor: DAL1.RBSS_CS.Bifunctors.XorBifunctor
useIntervalForSync: true
syncIntervalMs: -1
branchingFactor: 2
itemSize: 1
p2pStructure: RING