/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Models.RBB_CS
{
    /// <summary>
    /// ValidateStep
    /// </summary>
    [DataContract]
        public partial class ValidateStep : AbstractStep, IEquatable<ValidateStep>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateStep" /> class.
        /// </summary>
        /// <param name="idFrom">idFrom.</param>
        /// <param name="idTo">idTo.</param>
        /// <param name="fpOfData">fpOfData.</param>
        public ValidateStep(string idFrom = default(string), string idTo = default(string), string fpOfData = default(string))
        {
            this.IdFrom = idFrom;
            this.IdTo = idTo;
            this.FpOfData = fpOfData;
        }
        
        /// <summary>
        /// Gets or Sets FpOfData
        /// </summary>
        [DataMember(Name="fpOfData", EmitDefaultValue=false)]
        public string FpOfData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValidateStep {\n");
            sb.Append("  IdFrom: ").Append(IdFrom).Append("\n");
            sb.Append("  IdTo: ").Append(IdTo).Append("\n");
            sb.Append("  FpOfData: ").Append(FpOfData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ValidateStep);
        }

        /// <summary>
        /// Returns true if ValidateStep instances are equal
        /// </summary>
        /// <param name="input">Instance of ValidateStep to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidateStep input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IdFrom == input.IdFrom ||
                    (this.IdFrom != null &&
                    this.IdFrom.Equals(input.IdFrom))
                ) && 
                (
                    this.IdTo == input.IdTo ||
                    (this.IdTo != null &&
                    this.IdTo.Equals(input.IdTo))
                ) && 
                (
                    this.FpOfData == input.FpOfData ||
                    (this.FpOfData != null &&
                    this.FpOfData.Equals(input.FpOfData))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdFrom != null)
                    hashCode = hashCode * 59 + this.IdFrom.GetHashCode();
                if (this.IdTo != null)
                    hashCode = hashCode * 59 + this.IdTo.GetHashCode();
                if (this.FpOfData != null)
                    hashCode = hashCode * 59 + this.FpOfData.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
