/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SyncBody
    /// </summary>
    [DataContract]
        public partial class SyncBody :  IEquatable<SyncBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SyncBody" /> class.
        /// </summary>
        /// <param name="syncstate">Information about next steps, empty when done (required).</param>
        public SyncBody(AllOfsyncBodySyncstate syncstate = default(AllOfsyncBodySyncstate))
        {
            // to ensure "syncstate" is required (not null)
            if (syncstate == null)
            {
                throw new InvalidDataException("syncstate is a required property for SyncBody and cannot be null");
            }
            else
            {
                this.Syncstate = syncstate;
            }
        }
        
        /// <summary>
        /// Information about next steps, empty when done
        /// </summary>
        /// <value>Information about next steps, empty when done</value>
        [DataMember(Name="syncstate", EmitDefaultValue=false)]
        public AllOfsyncBodySyncstate Syncstate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SyncBody {\n");
            sb.Append("  Syncstate: ").Append(Syncstate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SyncBody);
        }

        /// <summary>
        /// Returns true if SyncBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SyncBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SyncBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Syncstate == input.Syncstate ||
                    (this.Syncstate != null &&
                    this.Syncstate.Equals(input.Syncstate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Syncstate != null)
                    hashCode = hashCode * 59 + this.Syncstate.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
