#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Org.OpenAPIToolsServer/ && \
    dotnet build src/Org.OpenAPIToolsServer/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Org.OpenAPIToolsServer/Org.OpenAPIToolsServer.csproj --launch-profile web"
