/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPIToolsServer.Converters;

namespace Org.OpenAPIToolsServer.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class InlineObject1 : IEquatable<InlineObject1>
    {
        /// <summary>
        /// The Id from what the sync process may start
        /// </summary>
        /// <value>The Id from what the sync process may start</value>
        [DataMember(Name="idFrom", EmitDefaultValue=false)]
        public string IdFrom { get; set; }

        /// <summary>
        /// The Id latest the sync process have to work
        /// </summary>
        /// <value>The Id latest the sync process have to work</value>
        [DataMember(Name="idNext", EmitDefaultValue=false)]
        public string IdNext { get; set; }

        /// <summary>
        /// The fingerprint for the data available
        /// </summary>
        /// <value>The fingerprint for the data available</value>
        [DataMember(Name="fpOfData", EmitDefaultValue=false)]
        public string FpOfData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject1 {\n");
            sb.Append("  IdFrom: ").Append(IdFrom).Append("\n");
            sb.Append("  IdNext: ").Append(IdNext).Append("\n");
            sb.Append("  FpOfData: ").Append(FpOfData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineObject1)obj);
        }

        /// <summary>
        /// Returns true if InlineObject1 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineObject1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject1 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IdFrom == other.IdFrom ||
                    IdFrom != null &&
                    IdFrom.Equals(other.IdFrom)
                ) && 
                (
                    IdNext == other.IdNext ||
                    IdNext != null &&
                    IdNext.Equals(other.IdNext)
                ) && 
                (
                    FpOfData == other.FpOfData ||
                    FpOfData != null &&
                    FpOfData.Equals(other.FpOfData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IdFrom != null)
                    hashCode = hashCode * 59 + IdFrom.GetHashCode();
                    if (IdNext != null)
                    hashCode = hashCode * 59 + IdNext.GetHashCode();
                    if (FpOfData != null)
                    hashCode = hashCode * 59 + FpOfData.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineObject1 left, InlineObject1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineObject1 left, InlineObject1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
