/*
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Models.RBB_CS
{
    /// <summary>
    /// Joining
    /// </summary>
    [DataContract(Name = "Joining")]
    public partial class Joining : IEquatable<Joining>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Joining" /> class.
        /// </summary>
        /// <param name="joiningIP">IP of the joining peer.</param>
        public Joining(string joiningIP = default(string))
        {
            this.JoiningIP = joiningIP;
        }

        /// <summary>
        /// IP of the joining peer
        /// </summary>
        /// <value>IP of the joining peer</value>
        [DataMember(Name = "joiningIP", EmitDefaultValue = false)]
        public string JoiningIP { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Joining {\n");
            sb.Append("  JoiningIP: ").Append(JoiningIP).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Joining);
        }

        /// <summary>
        /// Returns true if Joining instances are equal
        /// </summary>
        /// <param name="input">Instance of Joining to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Joining input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.JoiningIP == input.JoiningIP ||
                    (this.JoiningIP != null &&
                    this.JoiningIP.Equals(input.JoiningIP))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.JoiningIP != null)
                {
                    hashCode = (hashCode * 59) + this.JoiningIP.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
