/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AllOfinlineResponse200Syncstate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllOfinlineResponse200SyncstateTests
    {
        // TODO uncomment below to declare an instance variable for AllOfinlineResponse200Syncstate
        //private AllOfinlineResponse200Syncstate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllOfinlineResponse200Syncstate
            //instance = new AllOfinlineResponse200Syncstate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllOfinlineResponse200Syncstate
        /// </summary>
        [Test]
        public void AllOfinlineResponse200SyncstateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllOfinlineResponse200Syncstate
            //Assert.IsInstanceOfType<AllOfinlineResponse200Syncstate> (instance, "variable 'instance' is a AllOfinlineResponse200Syncstate");
        }



    }

}
