/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AllOfsyncBodySyncstate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AllOfsyncBodySyncstateTests
    {
        // TODO uncomment below to declare an instance variable for AllOfsyncBodySyncstate
        //private AllOfsyncBodySyncstate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AllOfsyncBodySyncstate
            //instance = new AllOfsyncBodySyncstate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AllOfsyncBodySyncstate
        /// </summary>
        [Test]
        public void AllOfsyncBodySyncstateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AllOfsyncBodySyncstate
            //Assert.IsInstanceOfType<AllOfsyncBodySyncstate> (instance, "variable 'instance' is a AllOfsyncBodySyncstate");
        }



    }

}
