/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SyncSteps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SyncStepsTests
    {
        // TODO uncomment below to declare an instance variable for SyncSteps
        //private SyncSteps instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SyncSteps
            //instance = new SyncSteps();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SyncSteps
        /// </summary>
        [Test]
        public void SyncStepsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SyncSteps
            //Assert.IsInstanceOfType<SyncSteps> (instance, "variable 'instance' is a SyncSteps");
        }


        /// <summary>
        /// Test the property 'TimeSent'
        /// </summary>
        [Test]
        public void TimeSentTest()
        {
            // TODO unit test for the property 'TimeSent'
        }
        /// <summary>
        /// Test the property 'Steps'
        /// </summary>
        [Test]
        public void StepsTest()
        {
            // TODO unit test for the property 'Steps'
        }

    }

}
