/* 
 * Range-Based Set Synchronization Framework
 *
 * This is a simple Framework to synchronize range-based sets.
 *
 * OpenAPI spec version: 0.1.0
 * Contact: u.kuehn@tu-berlin.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ValidateStep
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ValidateStepTests
    {
        // TODO uncomment below to declare an instance variable for ValidateStep
        //private ValidateStep instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ValidateStep
            //instance = new ValidateStep();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ValidateStep
        /// </summary>
        [Test]
        public void ValidateStepInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ValidateStep
            //Assert.IsInstanceOfType<ValidateStep> (instance, "variable 'instance' is a ValidateStep");
        }


        /// <summary>
        /// Test the property 'IdFrom'
        /// </summary>
        [Test]
        public void IdFromTest()
        {
            // TODO unit test for the property 'IdFrom'
        }
        /// <summary>
        /// Test the property 'IdTo'
        /// </summary>
        [Test]
        public void IdToTest()
        {
            // TODO unit test for the property 'IdTo'
        }
        /// <summary>
        /// Test the property 'FpOfData'
        /// </summary>
        [Test]
        public void FpOfDataTest()
        {
            // TODO unit test for the property 'FpOfData'
        }

    }

}
